#if !canImport(ObjectiveC)
import XCTest

extension FromSourceIntentionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FromSourceIntentionTests = [
        ("testIsVisibleFileprivateSymbol", testIsVisibleFileprivateSymbol),
        ("testIsVisibleInternalSymbol", testIsVisibleInternalSymbol),
        ("testIsVisiblePrivateConstructorAtSameFile", testIsVisiblePrivateConstructorAtSameFile),
        ("testIsVisiblePrivateGlobalVariableScopeSymbol", testIsVisiblePrivateGlobalVariableScopeSymbol),
        ("testIsVisiblePublicSymbol", testIsVisiblePublicSymbol),
        ("testPrivateMembersVisibleToExtensionsWithinSameFile", testPrivateMembersVisibleToExtensionsWithinSameFile),
    ]
}

extension FunctionBodyQueueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FunctionBodyQueueTests = [
        ("testQueueAllBodiesFound", testQueueAllBodiesFound),
        ("testQueueGlobalFunctionBody", testQueueGlobalFunctionBody),
        ("testQueueMethodBody", testQueueMethodBody),
        ("testQueuePropertyGetter", testQueuePropertyGetter),
        ("testQueuePropertyGetterAndSetter", testQueuePropertyGetterAndSetter),
    ]
}

extension IntentionSerializerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntentionSerializerTests = [
        ("testIntentionCollectionSerializationRoundtrip", testIntentionCollectionSerializationRoundtrip),
    ]
}

extension Intention_FileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Intention_FileTests = [
        ("testFunctionSignatureAsSelector", testFunctionSignatureAsSelector),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FromSourceIntentionTests.__allTests__FromSourceIntentionTests),
        testCase(FunctionBodyQueueTests.__allTests__FunctionBodyQueueTests),
        testCase(IntentionSerializerTests.__allTests__IntentionSerializerTests),
        testCase(Intention_FileTests.__allTests__Intention_FileTests),
    ]
}
#endif
