#if !canImport(ObjectiveC)
import XCTest

extension SwiftRewriterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftRewriterTests = [
        ("testIgnoreFollowImportsInPipedInputMode", testIgnoreFollowImportsInPipedInputMode),
        ("testPipedInput", testPipedInput),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftRewriterTests.__allTests__SwiftRewriterTests),
    ]
}
#endif
