#if !canImport(ObjectiveC)
import XCTest

extension QuickSpecPreprocessorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QuickSpecPreprocessorTests = [
        ("testAcceptsSpecBegin", testAcceptsSpecBegin),
        ("testBugReproCase", testBugReproCase),
        ("testInvalidCases", testInvalidCases),
        ("testIsWhitespaceTolerant", testIsWhitespaceTolerant),
        ("testPreprocessorEmptyInput", testPreprocessorEmptyInput),
        ("testPreprocessorPlainFile", testPreprocessorPlainFile),
        ("testQuickSpecFile", testQuickSpecFile),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(QuickSpecPreprocessorTests.__allTests__QuickSpecPreprocessorTests),
    ]
}
#endif
