#if !canImport(ObjectiveC)
import XCTest

extension SourceRangeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SourceRangeTests = [
        ("testInvalidSubstringIn", testInvalidSubstringIn),
        ("testLocationWithLocation", testLocationWithLocation),
        ("testUnion", testUnion),
        ("testUnionOutOrOrder", testUnionOutOrOrder),
        ("testUnionRangeWithLocation", testUnionRangeWithLocation),
        ("testValidSubstringIn", testValidSubstringIn),
    ]
}

extension SourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SourceTests = [
        ("testInvalidSourceAlwaysReturnsZeroForLineAndColumnQueries", testInvalidSourceAlwaysReturnsZeroForLineAndColumnQueries),
        ("testInvalidSourceIsEquatableToItself", testInvalidSourceIsEquatableToItself),
        ("testInvalidSourceIsNotEquatableToOtherSources", testInvalidSourceIsNotEquatableToOtherSources),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SourceRangeTests.__allTests__SourceRangeTests),
        testCase(SourceTests.__allTests__SourceTests),
    ]
}
#endif
