// Preprocessor directives found in file:
// #define ZX_PDF417_SYMBOL_TABLE_LEN 2787
// #define ZX_PDF417_BARS_IN_MODULE 8
var ZX_PDF417_SYMBOL_TABLE: UnsafePointer<CInt>!
let ZX_PDF417_NUMBER_OF_CODEWORDS: CInt
let ZX_PDF417_MIN_ROWS_IN_BARCODE: CInt
let ZX_PDF417_MAX_ROWS_IN_BARCODE: CInt
let ZX_PDF417_MAX_CODEWORDS_IN_BARCODE: CInt
let ZX_PDF417_MODULES_IN_CODEWORD: CInt
let ZX_PDF417_MODULES_IN_STOP_PATTERN: CInt
let ZX_PDF417_SYMBOL_TABLE_LEN: Int = 2787
let ZX_PDF417_BARS_IN_MODULE: Int = 8