#if !canImport(ObjectiveC)
import XCTest

extension DefaultSyntaxPassProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DefaultSyntaxPassProviderTests = [
        ("testDefaultSyntaxPasses", testDefaultSyntaxPasses),
    ]
}

extension StatementSpacingSyntaxPassTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StatementSpacingSyntaxPassTests = [
        ("testAddSpacingBetweenExpressionAndStatements", testAddSpacingBetweenExpressionAndStatements),
        ("testDontApplySpacingToFirstExpressionInMethod", testDontApplySpacingToFirstExpressionInMethod),
        ("testKeepExistingLeadingTrivia", testKeepExistingLeadingTrivia),
        ("testRewrite", testRewrite),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DefaultSyntaxPassProviderTests.__allTests__DefaultSyntaxPassProviderTests),
        testCase(StatementSpacingSyntaxPassTests.__allTests__StatementSpacingSyntaxPassTests),
    ]
}
#endif
