#if !canImport(ObjectiveC)
import XCTest

extension StringDiffTestingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringDiffTestingTests = [
        ("testDiffEmptyStrings", testDiffEmptyStrings),
        ("testDiffEqualStrings", testDiffEqualStrings),
        ("testDiffLargerExpectedString", testDiffLargerExpectedString),
        ("testDiffLargerResultString", testDiffLargerResultString),
        ("testDiffSimpleString", testDiffSimpleString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(StringDiffTestingTests.__allTests__StringDiffTestingTests),
    ]
}
#endif
